# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cesare Spinoso-Di Piano
email: cesare.spinoso@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  My name is Cesare Spinoso-Di Piano (Pronounced: "Chez-array" or just "Chez") and I'm a Master's Student at McGill
University in the Department of Computer Science. I am supervised by Dr. Jackie Cheung and Dr. Samira Rahimi. My 
research focuses on ways of applying natural language processing (NLP) to the field of medicine. We are currently working on using clinical reports to predict the degree of severity of appendicitises in patients pre-surgery. This would have implications in the way operations are scheduled to prioritize patients at a higher risk of developing complications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: something
github_username:  cesare-spinoso

# Build settings
markdown: kramdown
theme: jekyll-theme-slate
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
